# Schema for the configuration files of the Gevezoue theme.
gevezoue.settings:
  type: theme_settings
  label: 'Gevezoue settings'
  mapping:
    font_size:
      type: integer
      label: Font size
